### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'rocketlaunchlive'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'rocketlaunchlive'

### ISSUE THREAD

**Issue by LuckyTriple7** [djtimca/harocketlaunchlive#3]
https://developers.home-assistant.io/docs/creating_integration_manifest

**Comment by braetkuegeli** [comment]
No 'version' key in the manifest file for custom integration 'rocketlaunchlive'. As of **Home Assistant 2021.6**, this integration will no longer be loaded. Please report this to the maintainer of 'rocketlaunchlive'

**Comment by djtimca** [comment]
Fixed in release 008
